services:
  networks:
    java_net:
      driver:bridge
  
  java1:
    image: javac
    container_name: java1
    ports:
      -"101:3001"
    environment:
      - name=value
    env_file:
      - .env
    networks:
      - java_net
    


  