services:
  
  
  java1:
    image: java_c
    container_name: java1
    ports:
      - "101:3001"
    env_file:
      - .env
    networks:
      - java_net12
networks:
    java_net12:
      driver: bridge
    


  